name: studyflow
description: "Application de suivi des rÃ©visions"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  path: ^1.8.3
  intl: ^0.17.0
  charts_flutter: ^0.12.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  supabase_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fl_chart: ^0.66.2
  build_runner: ^2.4.7
  hive_generator: ^1.1.3 # <-- IMPORTANT

flutter:
  uses-material-design: true
