name: studyflow
description: "Application de suivi des rÃ©visions"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.17.0
  provider: ^6.1.1
  charts_flutter: ^0.12.0
  shared_preferences: ^2.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fl_chart: ^0.66.2

flutter:
  uses-material-design: true
  
